### ISSUE TITLE
Getting a couple of issues when running through both module and CLI 

### ISSUE THREAD

**Issue by Snazzyham** [MyIsaak/sqlitemongo#2] opened 2021-09-02 04:07 UTC
Getting 

`Failed to insert object with error MongoError: Invalid Operation, no operations specified`

Any idea why this may be?

**Comment by myisaak** [comment] 2021-09-03 09:06
Can you please describe how you were lead to this issue. I'm not able to reproduce it on my machine.

**Comment by myisaak** [comment] 2021-09-03 09:07
Also your environment details.

**Comment by ursomniac2** [comment] 2021-12-06 16:33
I have the same issue.   I'm trying to migrate from a Django-generated SQLite3 db/file into MongoDB.
What happens is that the first two tables load (auth_permission, django_admin_log) and then it dies with the aforementioned error.

I'm curious if the name space used for Django tables is confusing your script (i.e., we need to create multiple collections at the Django app level)?  (Or I'm just completely lost.).  In any case, the problem is repeatable.

**Comment by ursomniac2** [comment] 2021-12-06 16:34
Of course the two tables that DO load are ones that I completely don't need. :-)   It's basically all the other tables that are important (well, most of them).

**Comment by myisaak** [comment] 2021-12-07 10:41
Hi @ursomniac2 thanks for the info. I'll try again to reproduce this issue using your input.

**Comment by myisaak** [comment] 2021-12-07 10:56
It would be helpful if you can send me the db file, or its schema with list of table names

**Comment by myisaak** [comment] 2021-12-08 19:00
Ok I've pushed a fix upstream. Please let me know if it works now @ursomniac2 and @Snazzyham (Sorry for the long wait)

**Closed as completed** 2021-12-08 18:59 UTC
